### ISSUE TITLE
Workflow Dispatch e2e tests: Permissions error

### ISSUE THREAD

**Issue by asraa** [slsa-framework/example-package#110]
Are any of them running? 

See https://github.com/slsa-framework/example-package/actions/runs/3110439161

```
THIS_FILE: e2e.generic.workflow_dispatch.main.default.slsa3.yml
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/actions#create-a-workflow-dispatch-event"
}
```

**Comment by ianlewis** [comment]
aaaaaaahhhh!! curl doesn't fail with a non-zero exit code if the http request returns an error status.

https://github.com/slsa-framework/example-package/blob/adc5f34f6741da3d58e38d4f8516935857d52a9a/.github/workflows/scripts/e2e-dispatch.sh#L10-L13

We need to add `--fail` to those curl calls.
