### ISSUE TITLE
Container: Add a workflow for verifier e2e test generation 

### ISSUE THREAD

**Issue by asraa** [slsa-framework/example-package#115]
https://github.com/slsa-framework/slsa-github-generator/pull/1108

Similar to the other `.github/workflows/verifier-e2e*` workflows.

**Comment by ianlewis** [comment]
@asraa It's my understanding that this is done? can we close?
https://github.com/slsa-framework/example-package/blob/fad19efe32b5e360c1fb09f4701dac1dcdee8cc0/.github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml

**Comment by asraa** [comment]
yes!
