### ISSUE TITLE
Add SLSA v1.0 Provenance verification

### ISSUE THREAD

**Issue by asraa** [slsa-framework/example-package#150]
Using this to track progress here for 1.0 docker-based verification, so that for delegator you can reference it.

**Comment by asraa** [comment]
You can use this verify func
https://github.com/slsa-framework/example-package/blob/124d501fe3142b304e2e442728b0e3f9b175fc64/.github/workflows/scripts/e2e-verify.common.sh#L58

**Comment by ianlewis** [comment]
I think we do this now.
