### ISSUE TITLE
goreleaser example

### ISSUE THREAD

**Issue by developer-guy** [slsa-framework/example-package#165]
One of the use cases of using SLSA generators is generating artifacts with GoReleaser and using a generic generator to generate provenance, so, it'd be good to add an example of this to ensure that everything is working as we expected during new releases of both GoReleaser and generators. Maybe we could add draft-release support to test the new behavior https://github.com/slsa-framework/slsa-github-generator/issues/1476.

/cc @caarlos0

WDYT @ianlewis @laurentsimon @asraa ?

**Comment by asraa** [comment]
This would be a great example to add to ensure that there's no regression!

**Comment by laurentsimon** [comment]
+1, feel free to send us a PR (I had dded a comment for it too https://github.com/slsa-framework/slsa-github-generator/issues/1476#issuecomment-1495040754)
