### ISSUE TITLE
`container-based_build` job doesn't exist

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/example-package#206]
`container-based_build` job doesn't exist

https://github.com/slsa-framework/example-package/blob/3ca885249435de2572f9a498107d6d3dae8305cf/.github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml#LL168C12-L168C33

**Comment by asraa** [comment]
Can take care of it - this was a typo - it doesn't need that job. I'll update it so that it produces the correct output name, however.

**Comment by asraa** [comment]
Fixed by https://github.com/slsa-framework/example-package/commit/0c148774e84f617e06c16805451cddd753e78556
