### ISSUE TITLE
Feature: customizable builder name

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/example-package#21]
The builder name is currently hardcoded in https://github.com/slsa-framework/example-package/blob/main/.github/workflows/scripts/e2e-verify.sh#L143

We should make it parameterizable, e.g. via a `BUILDER` env variables declared in workflows.

This will allow us to support other builders

**Comment by laurentsimon** [comment]
Looks like we can close this, since it's handled via different scripts instead.
@ianlewis agreed?

**Comment by ianlewis** [comment]
Yeah, I'm not sure this is relevant anymore.
