### ISSUE TITLE
Failed Maven download of folder

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/example-package#282]
See https://github.com/slsa-framework/example-package/actions/runs/5930111718/job/16079231967

@AdamKorcz

**Comment by laurentsimon** [comment]
This error `c31d5ccc31df68ecc42ccf4149144866c47d8a
No artifact name specified, downloading all artifacts` indicates that the name of the artifact is empty, and the download falls back to downloading all artifacts, which may mess up with the downloaded folders.

The name being empty is typically due to the variable name not being correct, or not properly exported, etc

**Comment by AdamKorcz** [comment]
Might be related to https://github.com/slsa-framework/slsa-github-generator/pull/2668.

**Comment by laurentsimon** [comment]
Working now, thank you! https://github.com/slsa-framework/example-package/actions/runs/5930706522
