### ISSUE TITLE
Issues not closing

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/example-package#304]
This workflow (launched manually) https://github.com/slsa-framework/example-package/actions/runs/7660225164/workflow did not automatically close https://github.com/slsa-framework/slsa-github-generator/issues/3173

@ianlewis

**Comment by laurentsimon** [comment]
@ramonpetgrave64

**Comment by ianlewis** [comment]
> This workflow (launched manually) https://github.com/slsa-framework/example-package/actions/runs/7660225164/workflow did not automatically close [slsa-framework/slsa-github-generator#3173](https://github.com/slsa-framework/slsa-github-generator/issues/3173)
> 
> @ianlewis

Yeah, that is because the workflow is meant to test the `schedule` event type but if you run it manually it's given the `workflow_dispatch` event type. So it's set up so that it will run when triggered manually (for spot checks) but won't close bugs until the correct event type is used.
