### ISSUE TITLE
Upgrade upload/download-artifact in sync across all org

### ISSUE THREAD

**Issue by mihaimaruseac** [slsa-framework/example-package#320]
Because `upload-artifact` and `download-artifact` are not compatible across v3-v4 major bump, we need to upgrade them across all repos at the same time, instead of when Renovate opens a PR in one repo.

Probably also need to cut new releases for that.

**Comment by mihaimaruseac** [comment]
Opened https://github.com/slsa-framework/slsa-github-generator/issues/3239 to also make sure the main repo is in the known.

**Comment by ianlewis** [comment]
This is done.
