### ISSUE TITLE
Version release handling

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/example-package#40]
As we create more and more release, we may miss the latest release (we currently list 200 in the [script](https://github.com/slsa-framework/example-package/blob/main/.github/workflows/scripts/e2e-create-release.sh#L12)). I don't know how the results are ordered when querying the API. If it's chronological, we're fine. But I've already seen some versions being missed, so I suspect it's not...

We may want to delete releases on a regular basis to clean them up, once https://github.com/slsa-framework/example-package/issues/34 is resolved

**Comment by ianlewis** [comment]
This is resolved.

- We currently paginate through all releases using [`gh  api --method GET "/repos/$GITHUB_REPOSITORY/releases" --paginate`](https://github.com/slsa-framework/example-package/blob/4fbd8ee87d3da4244515195d0a4fdfd8695cce77/.github/workflows/scripts/e2e-create-release.sh#L67)
- We delete old releases daily: [schedule.delete-old-releases.yml](https://github.com/slsa-framework/example-package/blob/4fbd8ee87d3da4244515195d0a4fdfd8695cce77/.github/workflows/schedule.delete-old-releases.yml)
