### ISSUE TITLE
Validate that workflow names are unique

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/example-package#47]
The workflow name is used by several workflows, so we should ensure they are unique

**Comment by laurentsimon** [comment]
I have a better idea. Let's remove the `name:` field altogether. the `workflow` variables will be set to the workflow filename. Let's use it instead. When creating the issue, we can replace `.` by ` ` to make it more human-friendly.

The workflow name is "encoded" in its name, so let's use the filename instead. It's too easy to forget to update the name.

**Comment by laurentsimon** [comment]
the main drawback is the the UI now is terrible :/ the Action tab shows filename
But it seems to be working. Closing.
Let me know if the UI is so bad we should revert.

**Comment by ianlewis** [comment]
Yeah, it seems redundant that it shows the `.github/workflows` part of the path...

**Comment by laurentsimon** [comment]
yeah that's not ideal :/ but it fixes the original problem :)
Any other ideas?

Note that we can search by filename in the search box

**Comment by laurentsimon** [comment]
Thanks. Let's close this issue then.
