### ISSUE TITLE
Add link to workflow runs page in created issues

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/example-package#55]
e.g. https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.push.main.default.slsa3.yml

**Comment by laurentsimon** [comment]
We already have this, don't we? See https://github.com/slsa-framework/slsa-github-generator/issues/292 `Wokflow file`

**Comment by ianlewis** [comment]
That's a link to the file in the repo. What I'm proposing is adding a link the the workflow runs under the actions tab. Note the url `https://github.com/slsa-framework/example-package/actions/...`

**Comment by laurentsimon** [comment]
Got it, +1, seems super useful!

**Comment by ianlewis** [comment]
I'll add it today.

**Comment by laurentsimon** [comment]
I can do that now if you want.

**Comment by laurentsimon** [comment]
just pushed the change. Just a single line https://github.com/slsa-framework/example-package/commit/fc623f1993287cd538cb4cd0c01e546fdb06d81c

**Comment by ianlewis** [comment]
Sorry, had to do something else yesterday that took my attention for the day. Thanks for adding this!
