### ISSUE TITLE
Test for release assets for generic generator

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/example-package#87]
This is missing, let's add it.

**Comment by laurentsimon** [comment]
Renamed a workflow to https://github.com/slsa-framework/example-package/blob/11cb5e03b88cb79f95662f49c9622da8cc11b5cc/.github/workflows/e2e.generic.tag.main.assets.slsa3.yml and updated the scripts.
 
Checking whether everything works before closing this issue.

**Comment by ianlewis** [comment]
This seems to be working fine.
https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.main.assets.slsa3.yml
